export enum RideState {
  SELECT_RIDE = 'SELECT_RIDE',
  EXTRA_DETAILS = 'EXTRA_DETAILS',
  CONFIRM_RIDE = 'CONFIRM_RIDE',
  DRIVER_FOUND = 'DRIVER_FOUND',
  DRIVER_ARRIVED = 'DRIVER_ARRIVED',
  TRIP_STARTED = 'RIDE_STARTED',
  RIDE_ENDED = 'RIDE_ENDED',
}