export enum RideState {
  SELECT_RIDE = 'SELECT_RIDE',
  EXTRA_DETAILS = 'EXTRA_DETAILS',
  CONFIRM_RIDE = 'CONFIRM_RIDE',
  SEARCHING_FOR_DRIVER = 'SEARCHING_FOR_DRIVER',
  NO_DRIVER_FOUND = 'NO_DRIVER_FOUND',
  DRIVER_FOUND = 'DRIVER_FOUND',
  DRIVER_ARRIVED = 'DRIVER_ARRIVED',
  TRIP_STARTED = 'RIDE_STARTED',
  TRIP_ENDED = 'RIDE_ENDED',
}

export enum TripStatus {
  NULL = 'NULL',
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  PICKUP = 'PICKUP',
  ON_TRIP = 'ONTRIP',
  COMPLETED = 'COMPLETED',
  CANCELLED_BY_RIDER = 'CANCELLED_BY_RIDER',
  CANCELLED_BY_DRIVER = 'CANCELLED_BY_DRIVER',
}
