export enum RideState {
  SELECT_RIDE = 'SELECT_RIDE',
  EXTRA_DETAILS = 'EXTRA_DETAILS',
  CONFIRM_RIDE = 'CONFIRM_RIDE',
  DRIVER_FOUND = 'DRIVER_FOUND',
  DRIVER_ARRIVED = 'DRIVER_ARRIVED',
  TRIP_STARTED = 'RIDE_STARTED',
  RIDE_ENDED = 'RIDE_ENDED',
  CANCELLED = 'CANCELLED',
}


export enum TripStatus {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  PICKUP = 'PICKUP', 
  ON_TRIP = 'ONTRIP',
  COMPLETED = 'COMPLETED',
  CANCELLED_BY_RIDER = 'CANCELLED_BY_RIDER',
  CANCELLED_BY_DRIVER = 'CANCELLED_BY_DRIVER',
}